version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    deploy:
      replicas: 1 
    networks: 
    - pc_network
    ports:
    - target: 80
      published: 80 
      protocol: tcp
    volumes:
    - type: bind
      source: ./spring-petclinic-nginx/nginx.conf
      target: /etc/nginx/nginx.conf
      depends_on:
      - front-end
  frontend:
    container_name: spring-petclinic-angular
    build: ./spring-petclinic-angular
    image: nokdev/spring-petclinic-angular:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    depends_on:
      - backend
    networks: 
      - pc_network
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  backend:
    container_name: spring-petclinic-rest
    build: ./spring-petclinic-rest
    image: nokdev/spring-petclinic-rest:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    networks: 
      - pc_network
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
  db:
    build: ./spring-petclinic-db
    image: nokdev/spring-petclinic-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - petclinic-db:/var/lib/mysql
      
volumes:
  petclinic-db:

networks:
  pc_network:
    