version: "3.7"
services: 
  nginx:
    image: nokdev/spring-petclinic-nginx
    build:
      context: ./spring-petclinic-nginx/.
      dockerfile: Dockerfile
  mysql:
    image: nokdev/spring-petclinic-db:latest
    build: ./spring-petclinic-db/.
  backend:
    image: nokdev/spring-petclinic-rest:latest
    build:
      context: ./spring-petclinic-rest/.
      dockerfile: Dockerfile     
  frontend:
    image: nokdev/spring-petclinic-angular:latest
    build: 
      context: ./spring-petclinic-angular/.
      dockerfile: Dockerfile
  